### ISSUE TITLE
Make the plugin ready for translation?

### ISSUE THREAD

**Issue by BoweFrankema** [gordielachance/bbpress-votes#1]
Hi there,

I really like BBPress Votes and love how well it integrates into BBPress & BuddyPress. I'm running a multilingiual BuddyPress community and would like to see the plugin translated. Is this on the roadmap for a future version?

Thanks in advance,
Bowe

**Comment by gordielachance** [comment]
Yes, i'll do this soon !  Thanks for the feedback.

**Comment by gordielachance** [comment]
Ok, this is ready in 1.0.4 !
You can help translate on [oneskyapp](http://osjxryl.oneskyapp.com/admin/project/dashboard/project/63465).
