### ISSUE TITLE
bbpvotes_can_user_vote_down_for_post filter

### ISSUE THREAD

**Issue by clavaque** [gordielachance/bbpress-votes#4]
In function `bbpvotes_can_user_vote_down_for_post`, shouldn't the filter in the return line be `bbpvotes_can_user_vote_down_for_post`? https://github.com/gordielachance/bbpress-votes/blob/master/bbpvotes-template.php#L55

**Comment by gordielachance** [comment]
of course yes ! fixed.  https://github.com/gordielachance/bbpress-votes/commit/d86c3a3807aa0b042f0461ea3dc9c0c61e29f476
